[package]
name = "xfina"
version.workspace = true
edition.workspace = true

[workspace]
resolver = "2"
members = [
    "models",
    "mutual-funds/cams",
    "intl-stocks/ibkr",
    "wasm",
    "credit-cards/hdfc",
    "credit-cards/icici",
    "bank-accounts/hdfc",
    "bank-accounts/icici",
    "bank-accounts/sbi",
    "bank-accounts/bob",
    "bank-accounts/axis",
    "python",
    "cli"
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
xfina-models = { path = "models" }
serde = "1.0"
pdf-extract = "0.7"
csv = "1.3"
wasm-bindgen = "0.2"
serde_json = "1.0"
regex = "1.10"
chrono = "0.4"
serde_with = "3"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"

[dependencies]
xfina-models = { path = "models" }
xfina-mf-cams = { path = "mutual-funds/cams" }
xfina-intl-stocks-ibkr = { path = "intl-stocks/ibkr" }
xfina-cc-hdfc = { path = "credit-cards/hdfc" }
xfina-cc-icici = { path = "credit-cards/icici" }
xfina-ba-hdfc = { path = "bank-accounts/hdfc" }
xfina-ba-icici = { path = "bank-accounts/icici" }
xfina-ba-sbi = { path = "bank-accounts/sbi" }
xfina-ba-bob = { path = "bank-accounts/bob" }
xfina-ba-axis = { path = "bank-accounts/axis" }
