[package]
name = "xfina-cli"
version.workspace = true
edition.workspace = true
publish = true
description = "CLI tool for parsing Indian financial statements using the xfina suite."
license = "Apache-2.0"
repository = "https://github.com/sakthipriyan/xfina"

[[bin]]
name = "xfina"
path = "src/main.rs"

[dependencies]
xfina = { path = ".." }
clap = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
