[package]
name = "xfina-py"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "xfina"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module", "abi3-py38"] }
pythonize = "0.21"
serde_json = { workspace = true }

xfina = { path = ".." }
